version: '3.2'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgres/data
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    command: go run cmd/main.go -b 0.0.0.0